namespace SchoolErp.Application.Features.Students;

public static class StudentQueries
{
    public const string GetStudentById = @"
        SELECT s.STUDENT_ID, s.NAME, sc.CLASS_ID, sc.REGISTER_NO, sc.ROLL_NO, CAST(s.DATE_OF_BIRTH AS CHAR) as DATE_OF_BIRTH, s.USER_ID, 
               s.MOBILE_NO, s.FATHER_NAME, s.MOTHER_NAME, s.ADDRESS, s.ADMISSION_NO, s.EMAIL_ID, s.GENDER_ID,
               s.STATE_ID, s.NATIONALITY_ID,
               CAST(s.IS_ACTIVE AS CHAR) as IS_ACTIVE, CAST(s.IS_DELETED AS CHAR) as IS_DELETED, 
               CAST(s.CREATED_AT AS CHAR) as CREATED_AT
        FROM STUDENTS_INFO s
        LEFT JOIN STU_CLASS sc ON s.STUDENT_ID = sc.STUDENT_ID AND sc.IS_ACTIVE = 1 AND sc.IS_DELETED = 0
        WHERE s.STUDENT_ID = @Id AND s.IS_DELETED = 0;";

    public const string InsertStudent = @"
        INSERT INTO STUDENTS_INFO (STUDENT_ID, NAME, MOBILE_NO, FATHER_NAME, MOTHER_NAME, ADDRESS, ADMISSION_NO, EMAIL_ID, GENDER_ID, DATE_OF_BIRTH, STATE_ID, USER_ID, NATIONALITY_ID, IS_ACTIVE, IS_DELETED, CREATED_AT)
        VALUES (@STUDENT_ID, @NAME, @MOBILE_NO, @FATHER_NAME, @MOTHER_NAME, @ADDRESS, @ADMISSION_NO, @EMAIL_ID, @GENDER_ID, @DATE_OF_BIRTH, @STATE_ID, @USER_ID, @NATIONALITY_ID, @IS_ACTIVE, @IS_DELETED, @CREATED_AT);";

    public const string InsertStudentClass = @"
        INSERT INTO STU_CLASS (STU_CLASS_ID, STUDENT_ID, CLASS_ID, ACADEMIC_YEAR_ID, REGISTER_NO, ROLL_NO, IS_LEFT, IS_ACTIVE, IS_DELETED, CREATED_AT)
        VALUES (@STU_CLASS_ID, @STUDENT_ID, @CLASS_ID, @ACADEMIC_YEAR_ID, @REGISTER_NO, @ROLL_NO, 0, @IS_ACTIVE, @IS_DELETED, @CREATED_AT);";

    public const string UpdateStudent = @"
        UPDATE STUDENTS_INFO
        SET NAME = @NAME, MOBILE_NO = @MOBILE_NO, FATHER_NAME = @FATHER_NAME, MOTHER_NAME = @MOTHER_NAME, 
            ADDRESS = @ADDRESS, ADMISSION_NO = @ADMISSION_NO, EMAIL_ID = @EMAIL_ID, GENDER_ID = @GENDER_ID,
            DATE_OF_BIRTH = @DATE_OF_BIRTH, STATE_ID = @STATE_ID, NATIONALITY_ID = @NATIONALITY_ID, UPDATED_AT = @UPDATED_AT
        WHERE STUDENT_ID = @STUDENT_ID AND IS_DELETED = 0;";

    public const string UpdateStudentClass = @"
        UPDATE STU_CLASS
        SET CLASS_ID = @CLASS_ID, REGISTER_NO = @REGISTER_NO, ROLL_NO = @ROLL_NO, UPDATED_AT = @UPDATED_AT
        WHERE STUDENT_ID = @STUDENT_ID AND IS_ACTIVE = 1 AND IS_DELETED = 0;";

    public const string DeleteStudent = @"
        UPDATE STUDENTS_INFO SET IS_DELETED = 1, UPDATED_AT = @UPDATED_AT WHERE STUDENT_ID = @STUDENT_ID;";

    public const string DeleteStudentClass = @"
        UPDATE STU_CLASS SET IS_DELETED = 1, UPDATED_AT = @UPDATED_AT WHERE STUDENT_ID = @STUDENT_ID;";

    public const string GetAllStudents = @"
        SELECT s.STUDENT_ID, s.NAME, sc.CLASS_ID, sc.REGISTER_NO, sc.ROLL_NO, CAST(s.DATE_OF_BIRTH AS CHAR) as DATE_OF_BIRTH, s.USER_ID, 
               s.MOBILE_NO, s.FATHER_NAME, s.MOTHER_NAME, s.ADDRESS, s.ADMISSION_NO, s.EMAIL_ID, s.GENDER_ID,
               s.STATE_ID, s.NATIONALITY_ID,
               CAST(s.IS_ACTIVE AS CHAR) as IS_ACTIVE, CAST(s.IS_DELETED AS CHAR) as IS_DELETED, 
               CAST(s.CREATED_AT AS CHAR) as CREATED_AT
        FROM STUDENTS_INFO s
        LEFT JOIN STU_CLASS sc ON s.STUDENT_ID = sc.STUDENT_ID AND sc.IS_ACTIVE = 1 AND sc.IS_DELETED = 0
        WHERE s.IS_DELETED = 0 AND (@SearchTerm IS NULL OR s.NAME LIKE CONCAT('%', @SearchTerm, '%'))
        ORDER BY s.CREATED_AT DESC
        LIMIT @Limit OFFSET @Offset;";

    public const string GetTotalStudentsCount = @"
        SELECT COUNT(*) FROM STUDENTS_INFO WHERE IS_DELETED = 0 AND (@SearchTerm IS NULL OR NAME LIKE CONCAT('%', @SearchTerm, '%'));";
}
