CREATE DATABASE IF NOT EXISTS SchoolErpDb;
USE SchoolErpDb;
CREATE TABLE `ACADEMIC_YEAR` (
  `ACADEMIC_YEAR_ID` varchar(36) NOT NULL,
  `ACADEMIC_YEAR` varchar(36) NOT NULL,
  `FROM_DATE` DATE NOT NULL,
  `TO_DATE` DATE NOT NULL,
  `IS_ACTIVE` INT DEFAULT '0',
  PRIMARY KEY (`ACADEMIC_YEAR_ID`)
) ;

-- 1. USER_INFO
CREATE TABLE USER_INFO (
    USER_INFO_ID VARCHAR(36) PRIMARY KEY,
    EMAIL VARCHAR(256) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(512) NOT NULL,
    ROLE_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'Active',
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL
);

-- 2. ROLES
CREATE TABLE ROLES (
    ROLE_ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. USER_ROLES
CREATE TABLE USER_ROLES (
    USER_ID VARCHAR(36) NOT NULL,
    ROLE_ID VARCHAR(36) NOT NULL,
    ACADEMIC_YEAR_ID varchar(36) NOT NULL,
    IS_ACTIVE int(1) default '1',
    IS_DELETED int(1) default '0',
    PRIMARY KEY (USER_ID, ROLE_ID)
);

-- 3.5. MODULES
CREATE TABLE `modules` (
  `PARENT_ID` varchar(36) NOT NULL,
  `MODULE_NAME` varchar(100) NOT NULL,
  `ICON` varchar(50) DEFAULT NULL,
  `DISPLAY_ORDER` int DEFAULT '0',
  `IS_ACTIVE` int DEFAULT '1',
  `IS_DELETED` int DEFAULT '0',
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PARENT_ID`)
) ;

-- 4. MENUS
CREATE TABLE MENUS (
    MENU_ID VARCHAR(36) PRIMARY KEY,
    MENU_NAME VARCHAR(100) NOT NULL,
    MENU_URL VARCHAR(255) NOT NULL,
    ICON VARCHAR(50) NULL,
    PARENT_MENU_ID VARCHAR(36) NULL,
    DISPLAY_ORDER INT DEFAULT 0,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PARENT_MENU_ID) REFERENCES modules(PARENT_ID)
);

-- 5. ROLE_MENUS
CREATE TABLE ROLE_MENUS (
    ROLE_ID VARCHAR(36) NOT NULL,
    MENU_ID VARCHAR(36) NOT NULL,
    IS_ACTIVE int(1) default '1',
    IS_DELETED int(1) default '0',
    PRIMARY KEY (ROLE_ID, MENU_ID)
);

-- 6. STAFF_INFO (Formerly Teachers)
CREATE TABLE STAFF_INFO (
    STAFF_ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DEPARTMENT VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(36) NULL,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL
);

-- 7. CLASSES
CREATE TABLE CLASSES (
    CLASS_ID VARCHAR(36) PRIMARY KEY,
    CLASS_NAME VARCHAR(50) NOT NULL,
    SECTION VARCHAR(50) NOT NULL,
    TEACHER_ID VARCHAR(36) NULL,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL,
    FOREIGN KEY (TEACHER_ID) REFERENCES STAFF_INFO(STAFF_ID) ON DELETE SET NULL
);

-- 8. STUDENTS_INFO
CREATE TABLE STUDENTS_INFO (
    STUDENT_ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    MOBILE_NO VARCHAR(15) NOT NULL,
    FATHER_NAME VARCHAR(200) NOT NULL,
    MOTHER_NAME VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ADMISSION_NO VARCHAR(15) NOT NULL,
    EMAIL_ID VARCHAR(100) NOT NULL,
    GENDER_ID VARCHAR(10) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    STATE_ID VARCHAR(36) NULL,
    USER_ID VARCHAR(36) NULL,
    NATIONALITY_ID VARCHAR(36) NULL,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL
);
CREATE TABLE `STU_CLASS` (
  `STU_CLASS_ID` varchar(36) NOT NULL,
  `STUDENT_ID` varchar(36) NOT NULL,
  `CLASS_ID` varchar(36) NOT NULL,
  `ACADEMIC_YEAR_ID` varchar(36) NOT NULL,
  `REGISTER_NO` varchar(50) NOT NULL,
  `ROLL_NO` varchar(50) NOT NULL,
  `IS_LEFT` int DEFAULT '0',
  `IS_ACTIVE` int DEFAULT '1',
  `IS_DELETED` int DEFAULT '0',
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`STU_CLASS_ID`)
) ;
-- 9. SYSTEM_LOGS
CREATE TABLE SYSTEM_LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_LEVEL VARCHAR(20) NOT NULL,
    MESSAGE TEXT NOT NULL,
    STACK_TRACE TEXT NULL,
    SOURCE VARCHAR(255) NULL,
    USER_ID VARCHAR(36) NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 10. SUPPORT TABLES
CREATE TABLE SUP_GENDER (
    GENDER_ID VARCHAR(36) PRIMARY KEY,
    GENDER_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE STAFF_CATEGORY (
    CATEGORY_ID VARCHAR(36) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0
);

CREATE TABLE SUP_NATIONALITY (
    NATIONALITY_ID VARCHAR(36) PRIMARY KEY,
    NATIONALITY_NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SUP_RELIGION (
    RELIGION_ID VARCHAR(36) PRIMARY KEY,
    RELIGION_NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SUP_BLOOD_GROUP (
    BLOOD_ID VARCHAR(36) PRIMARY KEY,
    BLOOD_NAME VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE DEPARTMENTS (
    DEPT_ID VARCHAR(36) PRIMARY KEY,
    DEPT_NAME VARCHAR(100) NOT NULL UNIQUE,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0
);

-- Seed Support Data
INSERT INTO SUP_GENDER (GENDER_ID, GENDER_NAME) VALUES 
(UUID(), 'Male'), (UUID(), 'Female'), (UUID(), 'Other');

INSERT INTO STAFF_CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES 
(UUID(), 'Teaching'), (UUID(), 'Non-Teaching'), (UUID(), 'Administrative');

INSERT INTO SUP_NATIONALITY (NATIONALITY_ID, NATIONALITY_NAME) VALUES 
(UUID(), 'Indian'), (UUID(), 'American'), (UUID(), 'British');

INSERT INTO SUP_RELIGION (RELIGION_ID, RELIGION_NAME) VALUES 
(UUID(), 'Hindu'), (UUID(), 'Christian'), (UUID(), 'Muslim'), (UUID(), 'Sikh');

INSERT INTO SUP_BLOOD_GROUP (BLOOD_ID, BLOOD_NAME) VALUES 
(UUID(), 'A+'), (UUID(), 'B+'), (UUID(), 'O+'), (UUID(), 'AB+'), (UUID(), 'A-'), (UUID(), 'B-'), (UUID(), 'O-'), (UUID(), 'AB-');

INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES 
(UUID(), 'Mathematics'), (UUID(), 'Science'), (UUID(), 'English'), (UUID(), 'Sports'), (UUID(), 'Administrative');

-- 11. ATTENDANCE TABLES
CREATE TABLE `sup_attendance_type` (
  `ATTENDANCE_TYPE_ID` varchar(36) NOT NULL,
  `ATTENDANCE_TYPE_NAME` varchar(100) NOT NULL,
  `ATTENDANCE_TYPE_CODE` varchar(100) NOT NULL,
  `ORDER_NO` int(1) default '0',
  `COLOR_CODE` varchar(20) default 'fff',
  `IS_ACTIVE` int DEFAULT '1',
  `IS_DELETED` int DEFAULT '0',
  PRIMARY KEY (`ATTENDANCE_TYPE_ID`),
  UNIQUE KEY `ATTENDANCE_TYPE_CODE` (`ATTENDANCE_TYPE_CODE`)
) ;

CREATE TABLE `stu_attendance_entries` (
  `STU_ATTENDANCE_ID` varchar(36) NOT NULL,
  `STUDENT_ID` varchar(36) NOT NULL,
  `ATTENDANCE_DATE` date NOT NULL,
  `ATTENDANCE_TYPE_ID` varchar(36) NOT NULL,
  `ENTRY_ID` varchar(36) NOT NULL,
  `IS_ACTIVE` int DEFAULT '1',
  `IS_DELETED` int DEFAULT '0',
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`STU_ATTENDANCE_ID`),
  KEY `FK_STU_ATTENDANCE_STUDENT_ID` (`STUDENT_ID`),
  KEY `FK_STU_ATTENDANCE_ATTENDANCE_TYPE_ID` (`ATTENDANCE_TYPE_ID`),
  UNIQUE KEY `UQ_STU_ATTENDANCE_STUDENT_DATE` (`STUDENT_ID`, `ATTENDANCE_DATE`),
  CONSTRAINT `FK_STU_ATTENDANCE_ATTENDANCE_TYPE_ID` FOREIGN KEY (`ATTENDANCE_TYPE_ID`) REFERENCES `sup_attendance_type` (`ATTENDANCE_TYPE_ID`),
  CONSTRAINT `FK_STU_ATTENDANCE_STUDENT_ID` FOREIGN KEY (`STUDENT_ID`) REFERENCES `students_info` (`STUDENT_ID`)
) ;
  CREATE TABLE `subject_list` (
  `SUBJECT_ID` varchar(36) NOT NULL,
  `SUBJECT_CODE` varchar(36) NOT NULL,
  `SUBJECT_NAME` varchar(236) NOT NULL,
  `SUBJECT_TYPE_ID` varchar(36) NOT NULL,
  `IS_ACTIVE` int DEFAULT '1',
  `IS_DELETED` int DEFAULT '0',
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`SUBJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `class_subject_staff` (
  `CLASS_SUBJECT_STAFF_ID` varchar(36) NOT NULL,
  `STAFF_ID` varchar(36) NOT NULL,
  `CLASS_ID` varchar(36) NOT NULL,
  `SUBJECT_ID` varchar(36) NOT NULL,
  `ACADEMIC_YEAR_ID` varchar(36) NOT NULL,
  `MAX_HR_PER_WEEK` int DEFAULT '5',
  `IS_CLASS_INCHARGE` int DEFAULT '1',
  `IS_ACTIVE` int DEFAULT '1',
  `IS_DELETED` int DEFAULT '0',
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`CLASS_SUBJECT_STAFF_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Seed Attendance Types
INSERT INTO `sup_attendance_type` (`ATTENDANCE_TYPE_ID`, `ATTENDANCE_TYPE_NAME`, `ATTENDANCE_TYPE_CODE`) VALUES
(UUID(), 'Present', 'P'),
(UUID(), 'Absent', 'A'),
(UUID(), 'Late', 'L'),
(UUID(), 'Half Day', 'HD');

-- Indexes for performance optimization
CREATE INDEX IX_MENUS_PARENT ON MENUS(PARENT_MENU_ID);
CREATE INDEX IX_USER_ROLES_ACADEMIC ON USER_ROLES(ACADEMIC_YEAR_ID);
CREATE INDEX IX_STU_CLASS_ACADEMIC ON STU_CLASS(ACADEMIC_YEAR_ID);
CREATE INDEX IX_STUDENTS_ADMISSION ON STUDENTS_INFO(ADMISSION_NO);
CREATE INDEX IX_USER_INFO_STATUS ON USER_INFO(STATUS, IS_ACTIVE);


-- Seed Initial Data
INSERT INTO ROLES (ROLE_ID, NAME) VALUES 
('role-admin-id', 'Admin'),
('role-teacher-id', 'Teacher'),
('role-student-id', 'Student');

INSERT INTO `modules` (PARENT_ID, MODULE_NAME, ICON, DISPLAY_ORDER) VALUES
('mod-main', 'Main Menu', 'bi-house', 1),
('mod-mgmt', 'Management', 'bi-briefcase', 2),
('mod-sys', 'System', 'bi-cpu', 3);

INSERT INTO MENUS (MENU_ID, PARENT_MENU_ID, MENU_NAME, MENU_URL, ICON, DISPLAY_ORDER) VALUES
('menu-dash', 'mod-main', 'Dashboard', '/', 'bi-house-door', 1),
('menu-students', 'mod-mgmt', 'Students', '/student-management', 'bi-mortarboard', 2),
('menu-teachers', 'mod-mgmt', 'Staff', '/staff-management', 'bi-person-workspace', 3),
('menu-attendance', 'mod-mgmt', 'Attendance', '/student-attendance', 'bi-calendar-check', 4),
('menu-users', 'mod-sys', 'Users', '/users', 'bi-people', 5),
('menu-roles', 'mod-sys', 'Roles', '/roles', 'bi-shield-lock', 6),
('menu-academic-config', 'mod-sys', 'Academic Config', '/academic-config', 'bi-gear', 7);

INSERT INTO ROLE_MENUS (ROLE_ID, MENU_ID) VALUES
('role-admin-id', 'menu-dash'),
('role-admin-id', 'menu-students'),
('role-admin-id', 'menu-teachers'),
('role-admin-id', 'menu-attendance'),
('role-admin-id', 'menu-users'),
('role-admin-id', 'menu-roles'),
('role-admin-id', 'menu-academic-config'),
('role-teacher-id', 'menu-dash'),
('role-teacher-id', 'menu-students'),
('role-teacher-id', 'menu-attendance'),
('role-student-id', 'menu-dash');

-- 12. TIMETABLE MANAGEMENT


CREATE TABLE ROOMS (
    ROOM_ID VARCHAR(36) PRIMARY KEY,
    ROOM_NAME VARCHAR(100) NOT NULL, 
    ROOM_TYPE VARCHAR(50) NOT NULL, 
    CAPACITY INT NOT NULL,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0
);

CREATE TABLE TIMETABLE_CONFIG (
    CONFIG_ID VARCHAR(36) PRIMARY KEY,
    ACADEMIC_YEAR_ID VARCHAR(36) NOT NULL,
    DAYS_PER_WEEK INT DEFAULT 5, 
    PERIODS_PER_DAY INT DEFAULT 8,
    PERIOD_DURATION_MINS INT DEFAULT 45,
    DAY_ORDER_START_DATE DATE NULL,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    FOREIGN KEY (ACADEMIC_YEAR_ID) REFERENCES ACADEMIC_YEAR(ACADEMIC_YEAR_ID)
);

CREATE TABLE PERIODS (
    PERIOD_ID VARCHAR(36) PRIMARY KEY,
    CONFIG_ID VARCHAR(36) NOT NULL,
    PERIOD_NUMBER INT NOT NULL, 
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    IS_BREAK INT DEFAULT 0, 
    LABEL VARCHAR(50), 
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    FOREIGN KEY (CONFIG_ID) REFERENCES TIMETABLE_CONFIG(CONFIG_ID)
);



CREATE TABLE TIMETABLE_ENTRIES (
    ENTRY_ID VARCHAR(36) PRIMARY KEY,
    CLASS_ID VARCHAR(36) NOT NULL,
    PERIOD_ID VARCHAR(36) NOT NULL,
    DAY_OF_WEEK INT NOT NULL, 
    SUBJECT_ID VARCHAR(36),
    TEACHER_ID VARCHAR(36),
    ROOM_ID VARCHAR(36),
    IS_SUBSTITUTE INT DEFAULT 0,
    ORIGINAL_TEACHER_ID VARCHAR(36) NULL,
    IS_ACTIVE INT DEFAULT 1,
    IS_DELETED INT DEFAULT 0,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
    FOREIGN KEY (PERIOD_ID) REFERENCES PERIODS(PERIOD_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES subject_list(SUBJECT_ID),
    FOREIGN KEY (TEACHER_ID) REFERENCES STAFF_INFO(STAFF_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID),
    FOREIGN KEY (ORIGINAL_TEACHER_ID) REFERENCES STAFF_INFO(STAFF_ID)
);
CREATE TABLE SUP_DAY_ORDER (
    DAY_ID VARCHAR(36) not null  PRIMARY KEY,
    DAY_ORDER INT,-- 1,2,3,4,5
    DAY_ORDER_NAME VARCHAR(100), -- monday tuesday wed thurs friday
    REMARK VARCHAR(200)
);
-- Adding Timetable Menus
INSERT INTO MENUS (MENU_ID, PARENT_MENU_ID, MENU_NAME, MENU_URL, ICON, DISPLAY_ORDER) VALUES
('menu-timetable', 'mod-mgmt', 'Timetable', '/timetable', 'bi-calendar-week', 5),
('menu-timetable-config', 'mod-mgmt', 'Timetable Config', '/timetable/config', 'bi-calendar-range', 6);

INSERT INTO ROLE_MENUS (ROLE_ID, MENU_ID) VALUES
('role-admin-id', 'menu-timetable'),
('role-admin-id', 'menu-timetable-config'),
('role-teacher-id', 'menu-timetable'),
('role-student-id', 'menu-timetable');


